// blog-content.js
// Blog post metadata for the Journal index + post pages.
// Loaded via <script src="../js/blog-content.js"></script> alongside content.js

window.CONTENT = window.CONTENT || {};

CONTENT.blog = {
  posts: [
    {
      slug: "how-to-be-productive",
      title: "How To Flourish And Be Productive: The Other Side Of Languishing",
      excerpt: "Perhaps for the first time ever in human history is the whole world going through collective grief. There is uncertainty everywhere.",
      tag: "Stress & Burnout",
      date: "6 July 2021",
      readTime: "4 min read",
      author: "Nandini Keshwani",
      featured: false,
    },
    {
      slug: "men-in-mental-health-non-existent",
      title: "The ‘Men’ in Mental Health is Non-Existent",
      excerpt: "It has long been understood that mental health in India is still a stigma for many people.",
      tag: "Mental Health Basics",
      date: "6 July 2021",
      readTime: "6 min read",
      author: "Armeet Narang",
      featured: false,
    },
    {
      slug: "toxic-relationship-with-gaslighter",
      title: "Toxic Relationship with a Gaslighter",
      excerpt: "In the 1944 film Gas Light, Gregory manipulated his wife, Paula to a point where she no longer trusts her own sense and perceptions of reality.",
      tag: "Relationships",
      date: "6 July 2021",
      readTime: "2 min read",
      author: "Alina Tambuwala",
      featured: false,
    },
    {
      slug: "parent-your-child-the-right-way",
      title: "Parent Your Child The Right Way",
      excerpt: "There is a certain style of parenting these days which is messing up the children or impeding their chances to develop into their selves.",
      tag: "Parenting",
      date: "6 July 2021",
      readTime: "4 min read",
      author: "Dimple Kishnani",
      featured: false,
    },
    {
      slug: "control-your-anxiety",
      title: "5 Ways You Can Control Your Anxiety",
      excerpt: "After the outbreak of novel coronavirus, there has been a tremendous increase in mental health issues worldwide.",
      tag: "Anxiety",
      date: "6 July 2021",
      readTime: "7 min read",
      author: "Nandini Keshwani",
      featured: false,
    },
    {
      slug: "be-better-listener",
      title: "Follow These 9 Tips To Be A Better Listener",
      excerpt: "Yes, that is true. But is that enough? Psychologists say that it is not. So, what is needed to be a better listener?",
      tag: "Relationships",
      date: "6 July 2021",
      readTime: "3 min read",
      author: "Armeet Narang",
      featured: false,
    },
    {
      slug: "8-things-to-do-when-differences-aggravate",
      title: "8 Things To Do When Differences Aggravate",
      excerpt: "Life, as we know it, changes constantly. And even bigger changes follow when we have to shift to a new environment.",
      tag: "Relationships",
      date: "6 July 2021",
      readTime: "3 min read",
      author: "Alina Tambuwala",
      featured: false,
    },
    {
      slug: "coronavirus-vs-moron-a-virus",
      title: "6 Mental Healthcare Tips During Lockdown",
      excerpt: "We’re all going through a massive coronavirus outbreak which is bringing changes in our lives each day.",
      tag: "Stress & Burnout",
      date: "6 July 2021",
      readTime: "6 min read",
      author: "Dimple Kishnani",
      featured: false,
    },
    {
      slug: "10-simple-tips-to-manage-stress",
      title: "10 Simple Tips To Manage Stress",
      excerpt: "We know that stress affects our physiological health. However, sometimes, we do not realize that stress is affecting our mental health as well.",
      tag: "Stress & Burnout",
      date: "6 July 2021",
      readTime: "1 min read",
      author: "Nandini Keshwani",
      featured: false,
    },
    {
      slug: "6-steps-on-how-to-give-yourself-some-self-love",
      title: "6 Steps On How To Give Yourself Some Self-Love",
      excerpt: "There are times where we tend to beat ourselves up with negative self-talk.",
      tag: "Self-Care",
      date: "6 July 2021",
      readTime: "1 min read",
      author: "Armeet Narang",
      featured: false,
    },
    {
      slug: "how-to-get-out-of-your-comfort-zone",
      title: "How to get out of your comfort zone!",
      excerpt: "Life begins at the end of your comfort zone! Sometimes, we find ourselves unable to take a step outside of our comfort zone.",
      tag: "Self-Care",
      date: "6 July 2021",
      readTime: "1 min read",
      author: "Alina Tambuwala",
      featured: false,
    },
    {
      slug: "how-to-know-if-you-suffer-from-panic-disorder",
      title: "How To Know If You Suffer From Panic Disorder",
      excerpt: "Panic Disorder is a type of Anxiety Disorder diagnosed in an individual when they experience panic attacks out-of-the-blue.",
      tag: "Anxiety",
      date: "6 July 2021",
      readTime: "1 min read",
      author: "Dimple Kishnani",
      featured: false,
    },
    {
      slug: "4-things-to-expect-from-a-therapy-session",
      title: "4 Things To Expect from A Therapy Session",
      excerpt: "Have you always considered visiting a counselor but don't know what to expect? Or do you feel nervous, scared to see a professional?",
      tag: "Getting Started",
      date: "6 July 2021",
      readTime: "2 min read",
      author: "Nandini Keshwani",
      featured: false,
    },
    {
      slug: "depression-symptoms",
      title: "Symptoms Of Depression",
      excerpt: "What is depression Depression is the most common mental disorder which is more than just sadness.",
      tag: "Depression",
      date: "25 July 2021",
      readTime: "3 min read",
      author: "Armeet Narang",
      featured: false,
    },
    {
      slug: "depression-causes-effects",
      title: "Depression - Causes & Effects",
      excerpt: "What causes Depression While a lot of research has gone into depression and its causes, researchers have still not been able to pinpoint one certain…",
      tag: "Depression",
      date: "28 July 2021",
      readTime: "3 min read",
      author: "Alina Tambuwala",
      featured: false,
    },
    {
      slug: "depression-types",
      title: "Types Of Depression",
      excerpt: "The most common type of depression is Major Depressive Disorder or MDD.",
      tag: "Depression",
      date: "31 July 2021",
      readTime: "1 min read",
      author: "Dimple Kishnani",
      featured: false,
    },
    {
      slug: "depression-levels",
      title: "Levels Of Depression",
      excerpt: "While it is common and natural to feel low from time to time, depression causes feelings of hopelessness and sadness for prolonged times in individuals…",
      tag: "Depression",
      date: "4 August 2021",
      readTime: "2 min read",
      author: "Nandini Keshwani",
      featured: false,
    },
    {
      slug: "depression-tips-to-cope",
      title: "Tips For Coping With Depression",
      excerpt: "While those with severe depression might need a combination of antidepressants and therapy, those with mild and moderate depression might find some help…",
      tag: "Depression",
      date: "7 August 2021",
      readTime: "2 min read",
      author: "Armeet Narang",
      featured: false,
    },
    {
      slug: "online-counselling-advantages-disadvantages",
      title: "Online Counselling - Advantages & Disadvantages",
      excerpt: "What is Online Counselling One of the ways through which mental health professionals now connect with their clients is through online counselling.",
      tag: "Getting Started",
      date: "11 August 2021",
      readTime: "3 min read",
      author: "Alina Tambuwala",
      featured: false,
    },
    {
      slug: "anxiety-symptoms",
      title: "Symptoms Of Anxiety",
      excerpt: "What Is Anxiety The American Psychological Association (APA) has described anxiety as an emotion characterized by feelings of tension, worried thoughts,…",
      tag: "Anxiety",
      date: "14 August 2021",
      readTime: "4 min read",
      author: "Dimple Kishnani",
      featured: false,
    },
    {
      slug: "anxiety-causes-effects",
      title: "Anxiety – Causes & Effects",
      excerpt: "What Causes Anxiety There is no singular cause of anxiety and research has shown that different individuals have different causes of anxiety.",
      tag: "Anxiety",
      date: "18 August 2021",
      readTime: "3 min read",
      author: "Nandini Keshwani",
      featured: false,
    },
    {
      slug: "anxiety-types",
      title: "Types Of Anxiety",
      excerpt: "While certain symptoms of anxiety overlap the different types of anxiety, there are five major types of anxiety disorders.",
      tag: "Anxiety",
      date: "21 August 2021",
      readTime: "1 min read",
      author: "Armeet Narang",
      featured: false,
    },
    {
      slug: "anxiety-levels",
      title: "Levels Of Anxiety",
      excerpt: "While everyone has anxiety at one point or the other in their lives, and a certain amount of anxiety is normal, anxiety disorders are characterized by…",
      tag: "Anxiety",
      date: "25 August 2021",
      readTime: "2 min read",
      author: "Alina Tambuwala",
      featured: false,
    },
    {
      slug: "anxiety-tips-to-cope",
      title: "Tips for Coping With Anxiety",
      excerpt: "Sometimes. anxiety can become overwhelming for the individual, making it difficult to concentrate and focus on other aspects around them.",
      tag: "Anxiety",
      date: "28 August 2021",
      readTime: "3 min read",
      author: "Dimple Kishnani",
      featured: false,
    },
    {
      slug: "why-you-have-trouble-sleeping",
      title: "Why You Have Trouble Sleeping - Revenge Bedtime Procrastination",
      excerpt: "Why You Have Trouble Sleeping Have you ever stayed up late to catch up on an episode of your favourite series or catch up on your reading instead of going…",
      tag: "Self-Care",
      date: "4 September 2021",
      readTime: "4 min read",
      author: "Nandini Keshwani",
      featured: false,
    },
    {
      slug: "highly-sensitive-person",
      title: "Highly Sensitive Person - What It Means",
      excerpt: "If you have been hearing things like “you’re too sensitive”, “you need to get some thick skin”, “why do you take everything so personally” since…",
      tag: "Mental Health Basics",
      date: "11 September 2021",
      readTime: "4 min read",
      author: "Armeet Narang",
      featured: false,
    },
    {
      slug: "obsessive-compulsive-disorder-symptoms",
      title: "Symptoms Of Obsessive-Compulsive Disorder (OCD)",
      excerpt: "What is Obsessive-Compulsive Disorder (OCD) The American Psychiatric Association (APA) defines Obsessive-Compulsive Disorder (OCD) as a disorder in which…",
      tag: "OCD",
      date: "27 September 2021",
      readTime: "4 min read",
      author: "Alina Tambuwala",
      featured: false,
    },
    {
      slug: "ocd-causes-effects",
      title: "OCD – Causes & Effects",
      excerpt: "What causes Obsessive Compulsive Disorder Like many other mental disorders, the exact causes of OCD are not yet known.",
      tag: "OCD",
      date: "4 October 2021",
      readTime: "2 min read",
      author: "Dimple Kishnani",
      featured: false,
    },
    {
      slug: "ocd-obsessions-and-compulsions",
      title: "Combinations & Common Obsessions and Compulsions of OCD",
      excerpt: "OCD can be divided into different types based on the nature of the symptoms experienced.",
      tag: "OCD",
      date: "11 October 2021",
      readTime: "2 min read",
      author: "Nandini Keshwani",
      featured: false,
    },
    {
      slug: "ocd-tips-to-cope",
      title: "Tips for Coping with OCD",
      excerpt: "OCD, while not completely curable, can be treated. The focus area is usually reducing compulsive behaviours and helping with distressing thoughts.",
      tag: "OCD",
      date: "18 October 2021",
      readTime: "3 min read",
      author: "Armeet Narang",
      featured: false,
    },
    {
      slug: "need-for-queer-affirmative-therapy",
      title: "The Need for Queer-Affirmative Therapy",
      excerpt: "It’s June, which also happens to be Pride Month - and there’s no better way to start it off than by addressing the need for queer-affirmative therapy and…",
      tag: "LGBTQIA+",
      date: "27 June 2022",
      readTime: "3 min read",
      author: "Alina Tambuwala",
      featured: false,
    },
    {
      slug: "corrective-emotional-experiences-heal-trauma",
      title: "How Corrective Emotional Experiences Might Help Heal Trauma",
      excerpt: "When we talk about corrective emotional experiences, we’re referring to how your therapist would take you back to certain trauma-inducing experiences or…",
      tag: "Trauma",
      date: "2 July 2022",
      readTime: "3 min read",
      author: "Dimple Kishnani",
      featured: false,
    },
    {
      slug: "shadow-work-and-its-benefits",
      title: "What is Shadow Work and How Can It Benefit You?",
      excerpt: "It was Carl Jung, the great psychoanalyst who said “The brighter the light, the darker the shadow.” When we talk about shadows, we often associate it with…",
      tag: "Self-Care",
      date: "16 July 2022",
      readTime: "3 min read",
      author: "Nandini Keshwani",
      featured: false,
    },
    {
      slug: "everything-you-need-to-know-about-addiction",
      title: "Everything You Need to Know About Addiction",
      excerpt: "Addiction, or Substance Use Disorder (SUD) is a complex condition that affects the brain and has many underlying causes.",
      tag: "Addiction",
      date: "21 August 2022",
      readTime: "6 min read",
      author: "Armeet Narang",
      featured: false,
    },
    {
      slug: "different-types-of-gender-identities",
      title: "What Are the Different Types of Gender Identities",
      excerpt: "Gender identity is very different from sexual identity.",
      tag: "LGBTQIA+",
      date: "15 September 2022",
      readTime: "2 min read",
      author: "Alina Tambuwala",
      featured: false,
    },
    {
      slug: "asexuality-in-lgbtqia",
      title: "Asexuality - The ‘A’ in LGBTQIA+",
      excerpt: "A lot has been written about the various facets that come under the umbrella of the queer community.",
      tag: "LGBTQIA+",
      date: "27 September 2022",
      readTime: "2 min read",
      author: "Dimple Kishnani",
      featured: false,
    },
    {
      slug: "coming-out-later-in-life",
      title: "Coming Out Later in Life",
      excerpt: "For many in the LGBTQIA+ community, coming out is often a long, tedious process that first starts with being honest with yourself, then slowly coming out…",
      tag: "LGBTQIA+",
      date: "13 October 2022",
      readTime: "4 min read",
      author: "Nandini Keshwani",
      featured: false,
    },
    {
      slug: "burnout-meaning",
      title: "Burnout Meaning | What Is Burnout",
      excerpt: "What is Burnout?",
      tag: "Stress & Burnout",
      date: "17 January 2025",
      readTime: "3 min read",
      author: "Armeet Narang",
      featured: false,
    },
    {
      slug: "trauma-informed-therapy",
      title: "Trauma Informed Therapy",
      excerpt: "What is Trauma-Informed Therapy?",
      tag: "Trauma",
      date: "17 January 2025",
      readTime: "4 min read",
      author: "Alina Tambuwala",
      featured: true,
    },
  ]
};
